### PR TITLE
Remove CfCli get orgs/spaces/apps methods

### PR DESCRIPTION
**Pull request by atwoosnam**
- this extension instead uses the CloudFoundryApiClient to get orgs/spaces/apps for these reasons:
  - performance (users of this extension will notice faster response times if making direct HTTP requests instead of invoking the CF CLI & parsing stdout)
  - accuracy (parsing HTTP responses is less error prone than parsing std output from the CF CLI & the format of HTTP responses is standardized/unlikely to change, which can't be said for the structure of CF CLI output)
  - the CF CLI exists in this extension as a convienient way to perform CF operations that are difficult to orchestrate manually (examples: pushing an app / authenitcating). Ideally this extension would not have a dependency on the CF CLI (because the executable is large & its API is subject to change), so the fewer CF CLI methods we depend on the better.

### CODE REVIEW

**Comment by ccheetham** [comment]
Need blanks lines in model impls for readability

**Comment by atwoosnam** [comment]
> Need blanks lines in model impls for readability

? I don't understand... which file(s) should be more readable?

**Review by zzori-theoriginal — APPROVED** [review]
looks good👍🏾

**Review by zzori-theoriginal — APPROVED** [review]
👍🏾

**Pull request merged**
