### PR TITLE
Fix bug that cleared bps instead of services

### LINKED ISSUE #320: Clicking "Clear" on Services clears Buildpacks
With the deployment window open and expanded
* select one or more buildpacks
* optionally select one or more services
* click "Clear" in the services area
* notice buildpack selections cleared out while services selections are not

### PR DESCRIPTION
**Pull request by atwoosnam**
fixes #320

### CODE REVIEW

**Comment by TimHess** [comment]
I think the same kind of issue is present on lines 642-643 also that should fix the checkboxes

**Review by ccheetham — APPROVED** [review]
lgtm

**Comment by atwoosnam** [comment]
@TimHess turns out the "`SelectedBuildpacksStringListConverter`" was working fine, just named in a misleading way :) 
In addition to tracking down the actual reason services were getting applied to the list of selected buildpacks, I also changed the name of that converter to be more accurate to what it actually does now

**Review by TimHess — APPROVED** [review]
LGTM

**Pull request merged**
